config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#index"
  
  resources :clients
  

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
   
   def index
       @clients = Client.all.reverse
   end
   
   def new
       @new_client = Client.new
   end
   
   def create
       @new_client = Client.create(client_params)
       if @new_client.save
           redirect_to root_path
       else
           render :new
       end
   end
   
   private
   def client_params
       params.require(:client).permit(:name, :age)
   end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   
   def index
       @name = "Leonardo"
   end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/index.html.erb
<h1>Cliens using this service</h1>

<%= link_to "New client", new_client_path %>

<table>
    <tr>
        <td>Name</td>
        <td>Age</td>
    </tr>
    <% @clients.each do |client| %>
        <tr>
            <td><%= client.name %></td>
            <td><%= client.age %></td>
        </tr>
    <% end %>
</table>

app/views/clients/new.html.erb
<h1>Creating a new client on system</h1>

<%= form_for @new_client do |new_client| %>
    <%= new_client.text_field :name, placeholder: "Name" %>
    <%= new_client.text_field :age, placeholder: "Age" %>
    <%= new_client.submit "Send" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>
<p>My name is <%= @name %></p>

<%= link_to "Clients", clients_path %>